[package]
name = "nodera-project"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nodera-core.workspace = true
nodera-markdown.workspace = true
nodera-parser-core.workspace = true
rusqlite.workspace = true
sha2.workspace = true
chrono.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
